<?php

use BuzzingPixel\Queue\QueueItemWithKey;
use BuzzingPixel\Templating\TemplateEngine;

assert($this instanceof TemplateEngine);

/** @noinspection PhpUndefinedVariableInspection */
assert(is_string($breadcrumbs));

/** @noinspection PhpUndefinedVariableInspection */
assert($queueItem instanceof QueueItemWithKey);
?>

<?=$breadcrumbs?>

<div class="py-6">
    <div class="overflow-hidden bg-white shadow-sm ring-1 ring-gray-900/5 rounded-xl mb-12 p-4">
        <div class="px-4 sm:px-0">
            <h3 class="text-base font-semibold leading-7 text-gray-900">
                Item
            </h3>
            <p class="mt-1 max-w-2xl text-sm leading-6 text-gray-500">
                <?=$queueItem->name?>
            </p>
        </div>
        <div class="mt-6">
            <dl class="grid grid-cols-1 sm:grid-cols-2">
                <div class="border-t border-gray-100 px-4 py-6 sm:col-span-2 sm:px-0">
                    <dt class="text-sm font-medium leading-6 text-gray-900">Key</dt>
                    <dd class="mt-1 text-sm leading-6 text-gray-700 sm:mt-2">
                        <?=$queueItem->key?>
                    </dd>
                </div>
                <div class="border-t border-gray-100 px-4 py-6 sm:col-span-1 sm:px-0">
                    <dt class="text-sm font-medium leading-6 text-gray-900">Queue</dt>
                    <dd class="mt-1 text-sm leading-6 text-gray-700 sm:mt-2">
                        <?=$queueItem->queueName?>
                    </dd>
                </div>
                <div class="border-t border-gray-100 px-4 py-6 sm:col-span-1 sm:px-0">
                    <dt class="text-sm font-medium leading-6 text-gray-900">Handle</dt>
                    <dd class="mt-1 text-sm leading-6 text-gray-700 sm:mt-2">
                        <?=$queueItem->handle?>
                    </dd>
                </div>
                <div class="border-t border-gray-100 px-4 py-6 sm:col-span-2 sm:px-0">
                    <dt class="text-sm font-medium leading-6 text-gray-900">Jobs</dt>
                    <dd class="mt-2 text-sm text-gray-900">
                        <ul role="list" class="divide-y divide-gray-100 rounded-md border border-gray-200">
                            <?php foreach ($queueItem->jobs->queueItemJobs as $job): ?>
                                <li class="py-4 pl-4 pr-5 text-sm leading-6">
                                    <div class="font-medium block pb-2">
                                        <?=$job->class?>::<?=$job->method?>
                                    </div>
                                    <pre class="p-8 bg-gray-700 text-amber-300"><code><?=json_encode($job->context, JSON_PRETTY_PRINT)?></code></pre>
                                </li>
                            <?php endforeach; ?>
                        </ul>
                    </dd>
                </div>
            </dl>
        </div>
    </div>
</div>
