<?php

use BuzzingPixel\Queue\QueueItemFailed;
use BuzzingPixel\Templating\TemplateEngine;

assert($this instanceof TemplateEngine);

/** @noinspection PhpUndefinedVariableInspection */
assert(is_string($breadcrumbs));

/** @noinspection PhpUndefinedVariableInspection */
assert($queueItem instanceof QueueItemFailed);

/** @noinspection PhpUndefinedVariableInspection */
assert(is_string($retryFailedUrl));
?>

<?=$breadcrumbs?>

<div class="py-6">
    <div class="overflow-hidden bg-white shadow-sm ring-1 ring-gray-900/5 rounded-xl mb-12 p-4">
        <div class="pb-5 sm:flex sm:items-center sm:justify-between">
            <div>
                <h3 class="text-base font-semibold leading-7 text-gray-900">
                    Item
                </h3>
                <p class="mt-1 max-w-2xl text-sm leading-6 text-gray-500">
                    <?=$queueItem->queueItem->name?>
                </p>
            </div>
            <div class="mt-3 flex sm:ml-4 sm:mt-0">
                <?php
                    $buttonClasses = [
                        'inline-flex,',
                        'items-center',
                        'rounded-md',
                        'px-3',
                        'py-2',
                        'text-sm',
                        'font-semibold',
                        'text-white',
                        'shadow-sm',
                        'focus-visible:outline',
                        'focus-visible:outline-2',
                        'focus-visible:outline-offset-2',
                    ];

                    if ($queueItem->retried) {
                        $buttonText = 'Already Retried';

                        $buttonClasses[] = 'bg-gray-300';
                    } else {
                        $buttonText = 'Retry';

                        $buttonClasses[] = 'bg-emerald-600';
                        $buttonClasses[] = 'hover:bg-emerald-500';
                    }
                ?>
                <form
                    action="<?=$retryFailedUrl?>"
                    method="POST"
                >
                    <button
                        type="submit"
                        class="<?=implode(' ', $buttonClasses)?>"
                        <?php if ($queueItem->retried): ?>
                        disabled
                        <?php endif; ?>
                    >
                        <?=$buttonText?>
                    </button>
                </form>
            </div>
        </div>
        <div class="">
            <dl class="grid grid-cols-1 sm:grid-cols-2">
                <div class="border-t border-gray-100 px-4 py-6 sm:col-span-2 sm:px-0">
                    <dt class="text-sm font-medium leading-6 text-gray-900">Failed Item Key</dt>
                    <dd class="mt-1 text-sm leading-6 text-gray-700 sm:mt-2">
                        <?=$queueItem->key?>
                    </dd>
                </div>
                <div class="border-t border-gray-100 px-4 py-6 sm:col-span-2 sm:px-0">
                    <dt class="text-sm font-medium leading-6 text-gray-900">Original Key</dt>
                    <dd class="mt-1 text-sm leading-6 text-gray-700 sm:mt-2">
                        <?=$queueItem->queueItem->key?>
                    </dd>
                </div>
                <div class="border-t border-gray-100 px-4 py-6 sm:col-span-1 sm:px-0">
                    <dt class="text-sm font-medium leading-6 text-gray-900">Queue</dt>
                    <dd class="mt-1 text-sm leading-6 text-gray-700 sm:mt-2">
                        <?=$queueItem->queueItem->queueName?>
                    </dd>
                </div>
                <div class="border-t border-gray-100 px-4 py-6 sm:col-span-1 sm:px-0">
                    <dt class="text-sm font-medium leading-6 text-gray-900">Handle</dt>
                    <dd class="mt-1 text-sm leading-6 text-gray-700 sm:mt-2">
                        <?=$queueItem->queueItem->handle?>
                    </dd>
                </div>
                <div class="border-t border-gray-100 px-4 py-6 sm:col-span-2 sm:px-0">
                    <dt class="text-sm font-medium leading-6 text-gray-900">Jobs</dt>
                    <dd class="mt-2 text-sm text-gray-900">
                        <ul role="list" class="divide-y divide-gray-100 rounded-md border border-gray-200">
                            <?php foreach ($queueItem->queueItem->jobs->queueItemJobs as $job): ?>
                                <li class="py-4 pl-4 pr-5 text-sm leading-6">
                                    <div class="font-medium block pb-2">
                                        <?=$job->class?>::<?=$job->method?>
                                    </div>
                                    <pre class="p-8 bg-gray-700 text-amber-300 overflow-x-scroll"><code><?=json_encode($job->context, JSON_PRETTY_PRINT)?></code></pre>
                                </li>
                            <?php endforeach; ?>
                        </ul>
                    </dd>
                </div>
                <div class="border-t border-gray-100 px-4 py-6 sm:col-span-1 sm:px-0">
                    <dt class="text-sm font-medium leading-6 text-gray-900">Message</dt>
                    <dd class="mt-1 text-sm leading-6 text-gray-700 sm:mt-2">
                        <?=$queueItem->message?>
                    </dd>
                </div>
                <div class="border-t border-gray-100 px-4 py-6 sm:col-span-1 sm:px-0">
                    <dt class="text-sm font-medium leading-6 text-gray-900">Code</dt>
                    <dd class="mt-1 text-sm leading-6 text-gray-700 sm:mt-2">
                        <?=$queueItem->code?>
                    </dd>
                </div>
                <div class="border-t border-gray-100 px-4 py-6 sm:col-span-1 sm:px-0">
                    <dt class="text-sm font-medium leading-6 text-gray-900">File</dt>
                    <dd class="mt-1 text-sm leading-6 text-gray-700 sm:mt-2">
                        <?=$queueItem->file?>
                    </dd>
                </div>
                <div class="border-t border-gray-100 px-4 py-6 sm:col-span-1 sm:px-0">
                    <dt class="text-sm font-medium leading-6 text-gray-900">Line</dt>
                    <dd class="mt-1 text-sm leading-6 text-gray-700 sm:mt-2">
                        <?=$queueItem->line?>
                    </dd>
                </div>
                <div class="border-t border-gray-100 px-4 py-6 sm:col-span-2 sm:px-0">
                    <dt class="text-sm font-medium leading-6 text-gray-900">Trace</dt>
                    <dd class="mt-1 text-sm leading-6 text-gray-700 sm:mt-2">
                        <pre class="p-8 bg-gray-700 text-amber-300 overflow-x-scroll"><code><?=$queueItem->trace?></code></pre>
                    </dd>
                </div>
            </dl>
        </div>
    </div>
</div>
