<?php

/** @noinspection PhpUndefinedVariableInspection */

use BuzzingPixel\Queue\Http\SidebarLinksCollection;
use BuzzingPixel\Templating\TemplateEngine;

assert($this instanceof TemplateEngine);
assert($sidebarLinks instanceof SidebarLinksCollection);
?>

<div class="flex grow flex-col gap-y-5 overflow-y-auto bg-white px-6 pb-4 border-r border-gray-200">
    <nav class="flex flex-1 flex-col">
        <ul role="list" class="-mx-2 space-y-1 mt-4">
            <?php foreach ($sidebarLinks->links as $link): ?>
                <?php
                    $linkClasses = [
                        'group',
                        'flex',
                        'gap-x-3',
                        'rounded-md',
                        'p-2',
                        'text-sm',
                        'leading-6',
                        'font-semibold',
                    ];

                    if ($link->isActive) {
                        $linkClasses = array_merge($linkClasses, [
                            'bg-gray-200',
                            'text-indigo-600',
                        ]);
                    } else {
                        $linkClasses = array_merge($linkClasses, [
                            'text-gray-700',
                            'hover:text-indigo-600',
                            'hover:bg-gray-200',
                        ]);
                    }
                ?>
                <li>
                    <a
                        href="<?=$link->href?>"
                        class="<?=implode(' ', $linkClasses)?>"
                    >
                        <?=$link->content?>
                    </a>
                </li>
            <?php endforeach; ?>
        </ul>
    </nav>
</div>
