<?php

/** @noinspection PhpUndefinedVariableInspection */

use BuzzingPixel\Queue\Http\SidebarLinksCollection;
use BuzzingPixel\Templating\TemplateEngine;

assert($this instanceof TemplateEngine);
assert($sidebarLinks instanceof SidebarLinksCollection);
?>

<div class="flex grow flex-col gap-y-5 overflow-y-auto bg-white px-6 pb-4 border-r border-gray-200">
    <nav class="flex flex-1 flex-col">
        <ul role="list" class="-mx-2 space-y-1 mt-2">
            <?php foreach ($sidebarLinks->links as $link): ?>
                <li>
                    <?php // Current: "bg-gray-50 text-indigo-600", Default: "text-gray-700 hover:text-indigo-600 hover:bg-gray-50" ?>
                    <?php // class="bg-gray-50 text-indigo-600 group flex gap-x-3 rounded-md p-2 text-sm leading-6 font-semibold" ?>
                    <a
                        href="<?=$link->href?>"
                        class="text-gray-700 hover:text-indigo-600 hover:bg-gray-50 group flex gap-x-3 rounded-md p-2 text-sm leading-6 font-semibold"
                    >
                        <?=$link->content?>
                    </a>
                </li>
            <?php endforeach; ?>
        </ul>
    </nav>
</div>
