<?php

use BuzzingPixel\Queue\Http\Completed\Tabs;
use BuzzingPixel\Templating\TemplateEngine;

assert($this instanceof TemplateEngine);

/** @noinspection PhpUndefinedVariableInspection */
assert($tabs instanceof Tabs);
?>

<nav class="-mb-px flex space-x-8">
    <?php foreach ($tabs->items as $tab): ?>
        <?php if ($tab->isActive): ?>
            <a
                href="?queue=<?=$tab->key?>"
                class="border-emerald-500 text-emerald-600 whitespace-nowrap border-b-2 px-1 pb-4 text-sm font-medium"
                aria-current="page"
            >
                <?=$tab->name?>
            </a>
        <?php else: ?>
            <a
                href="?queue=<?=$tab->key?>"
                class="border-transparent text-gray-500 hover:border-gray-300 hover:text-gray-700 whitespace-nowrap border-b-2 px-1 pb-4 text-sm font-medium"
            >
                <?=$tab->name?>
            </a>
        <?php endif; ?>
    <?php endforeach; ?>
</nav>
