<?php


use BuzzingPixel\Queue\Http\Failed\Details\DetailsUrlFactory;
use BuzzingPixel\Queue\QueueNameWithFailedItemsCollection;
use BuzzingPixel\Templating\TemplateEngine;

assert($this instanceof TemplateEngine);

/** @noinspection PhpUndefinedVariableInspection */
assert($timezone instanceof DateTimeZone);

/** @noinspection PhpUndefinedVariableInspection */
assert(is_string($dateFormat));

/** @noinspection PhpUndefinedVariableInspection */
assert($items instanceof QueueNameWithFailedItemsCollection);

/** @noinspection PhpUndefinedVariableInspection */
assert($detailsUrlFactory instanceof DetailsUrlFactory);

/** @noinspection PhpUndefinedVariableInspection */
assert(is_string($heading));
?>

<?=$heading?>

<?php if ($items->count() < 1): ?>
    <div class="relative block w-full rounded-lg border-2 border-dashed border-gray-300 p-12 text-center">
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="mx-auto h-12 w-12 text-gray-400">
            <path stroke-linecap="round" stroke-linejoin="round" d="M3.75 12h16.5m-16.5 3.75h16.5M3.75 19.5h16.5M5.625 4.5h12.75a1.875 1.875 0 0 1 0 3.75H5.625a1.875 1.875 0 0 1 0-3.75Z" />
        </svg>
        <span class="mt-2 block text-sm font-semibold text-gray-900">
            No matching queues found
        </span>
    </div>
<?php endif; ?>

<?php foreach ($items->items as $queue): ?>
    <div class="overflow-hidden bg-white shadow-sm ring-1 ring-gray-900/5 rounded-xl mb-12">
        <div class="border-b border-gray-200 bg-gray-50 px-4 py-5 sm:px-6">
            <h3 class="text-base leading-6 text-gray-900">
                <span class="font-semibold">Queue:</span>
                <span class="text-emerald-600"><?=$queue->queueName?></span>
            </h3>
        </div>
        <ul role="list" class="divide-y divide-gray-100">
            <?php if ($queue->items->count() < 1): ?>
                <li class="relative flex justify-between gap-x-6 px-4 py-2 sm:px-6 font-extralight">
                    no failed items from queue
                </li>
            <?php endif; ?>
            <?php foreach ($queue->items->items as $failedItem): ?>
                <li class="relative flex justify-between gap-x-6 px-4 py-5 hover:bg-green-100 sm:px-6">
                    <div class="flex min-w-0 gap-x-4">
                        <div class="min-w-0 flex-auto">
                            <p class="text-sm font-semibold leading-6 text-gray-900">
                                <a href="<?=$detailsUrlFactory->make($failedItem->key)?>">
                                    <span class="absolute inset-x-0 -top-px bottom-0"></span>
                                    <?=$failedItem->queueItem->name?>
                                </a>
                            </p>
                            <p class="mt-1 flex text-xs leading-5 text-gray-500">
                                <span class="font-semibold mr-1">Handle:</span>
                                <span class="text-emerald-600"><?=$failedItem->queueItem->handle?></span>
                            </p>
                            <p class="mt-1 flex text-xs leading-5 text-gray-500 sm:hidden">
                                <span class="font-semibold mr-1">Finished:</span>
                                <span class="text-emerald-600">
                                    <?=$failedItem->date
                                        ->setTimezone($timezone)
                                        ->format($dateFormat)?>
                                </span>
                            </p>
                        </div>
                    </div>
                    <div class="flex shrink-0 items-center gap-x-4">
                        <div class="hidden sm:flex sm:flex-col sm:items-end">
                            <p class="text-sm leading-6 text-gray-900 font-semibold">
                                Failed <?php if ($failedItem->retried): ?>(retried)<?php endif; ?>
                            </p>
                            <p class="mt-1 text-xs leading-5 text-emerald-600">
                                <?=$failedItem->date
                                    ->setTimezone($timezone)
                                    ->format($dateFormat)?>
                            </p>
                        </div>
                        <svg class="h-5 w-5 flex-none text-gray-400" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                            <path fill-rule="evenodd" d="M7.21 14.77a.75.75 0 01.02-1.06L11.168 10 7.23 6.29a.75.75 0 111.04-1.08l4.5 4.25a.75.75 0 010 1.08l-4.5 4.25a.75.75 0 01-1.06-.02z" clip-rule="evenodd" />
                        </svg>
                    </div>
                </li>
            <?php endforeach; ?>
        </ul>
    </div>
<?php endforeach; ?>
